### ISSUE TITLE
Inference at the offline (no internet connection)

### ISSUE THREAD

**Issue by YoussephAhmed** [pzelasko/daseg#10]
Hi again :) I get this error if I try to make inference with no internet connection, looks like the problem is with the tokenizer, any clue about where to download the config.json and what path i have to change?
    **json.load(open(Path(model_path) / 'tokenizer_config.json'))
NotADirectoryError: [Errno 20] Not a directory: 'DA_model/checkpointepoch=8.ckpt/tokenizer_config.json'

**Comment by pzelasko** [comment]
Can you post the full stack trace? Did it work previously and what exactly changed if it did?

**Comment by YoussephAhmed** [comment]
here is the full stack 
Traceback (most recent call last):
  File "/media/youssef/main/adam.ai/repos_/ai-core-models/daseg/daseg/models/transformer_model.py", line 34, in from_path
    return TransformerModel.from_pl_checkpoint(model_path, device)
  File "/media/youssef/main/adam.ai/repos_/ai-core-models/daseg/daseg/models/transformer_model.py", line 63, in from_pl_checkpoint
    ckpt = torch.load(path, map_location='cpu')
  File "/home/youssef/anaconda3/envs/daseg/lib/python3.8/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/youssef/anaconda3/envs/daseg/lib/python3.8/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/youssef/anaconda3/envs/daseg/lib/python3.8/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/program/checkpointepoch=8.ckpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "swda_inference.py", line 21, in <module>
    model = TransformerModel.from_path(Path(model_path), device=device)
  File "/media/youssef/main/adam.ai/repos_/ai-core-models/daseg/daseg/models/transformer_model.py", line 46, in from_path
    **json.load(open(Path(model_path) / 'tokenizer_config.json'))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/program/checkpointepoch=8.ckpt/tokenizer_config.json'


I did not change anything this error was existing from first place, and thank you for your quick response

**Comment by pzelasko** [comment]
Does this path: `'/opt/program/checkpointepoch=8.ckpt'` exist on your system? The script could not find it.

**Comment by YoussephAhmed** [comment]
Sorry I was giving a wrong path directory but now I am giving it the right one to have this error

Traceback (most recent call last):
  File "swda_inference.py", line 21, in <module>
    model = TransformerModel.from_path(Path(model_path), device=device)
/transformer_model.py", line 46, in from_path
    **json.load(open(Path(model_path) / 'tokenizer_config.json'))
NotADirectoryError: [Errno 20] Not a directory: '/media/youssef/main/model/checkpointepoch=8.ckpt/tokenizer_config.json'

**Comment by pzelasko** [comment]
Is this the full stack trace? Looks like a partial with the real error happening in another exception (like in your previous message).

**Comment by YoussephAhmed** [comment]
The code tries to load the config from the model file itself and not from the directory, so I think we should use something like os.path.basedir() instead but I am still getting errors even after I found a way to download the tokenizer_config.json and tries to replace it, will send the full stack in a different comment

**Comment by YoussephAhmed** [comment]
![Screenshot from 2022-06-10 05-56-54](https://user-images.githubusercontent.com/22798967/172987476-15127b49-ca6f-4594-94fa-2ebbac1a7528.png)
this happens only if there is no internet connection and I am asking if there is any work around to download the tokenizer_config.json (already did) but can not find the code snippits to add this change

**Comment by pzelasko** [comment]
Yes, you can download any model from huggingface like this, and copy to the relevant location on your offline machine:

```
git lfs install
git clone https://huggingface.co/pzelasko/longformer-swda-nolower
```

See: https://huggingface.co/pzelasko/longformer-swda-nolower

**Comment by pzelasko** [comment]
Huggingface models (including tokenizers, configs, etc.) are being cached somewhere on disk, but I'm not sure where, you may want to check your $HOME directory for directories starting with `.` (or read their documentation)

**Comment by YoussephAhmed** [comment]
That fixes my issue I am able to run it locally now without an internet connection thank you for your help :)
