### ISSUE TITLE
Advice on training with custom data?

### ISSUE THREAD

**Issue by nuges01** [pzelasko/daseg#12]
Hi there Piotr,

I'm exploring your paper/approach for a custom dialog dataset as opposed to SWDA and MRDA. At first glance, your code appears quite tightly coupled with those two datasets. The dialog data that I'd like to test on is pretty simple - it has Speaker, Utterance, and a simple Label - without any of the other metadata present in SWDA. Can you please advise on the best approach for using your code on simpler data? I get lost figuring out how `DialogActCorpus.from_swda_path` produces a TensorDataset. Could you provide some advice regarding what would be sufficient for producing a TensorDataset for a dataset as described?

Thanks!

**Comment by pzelasko** [comment]
Assuming your dataset is a list of dicts with keys "utterance", "label", and "speaker", you'll want to do sth like the following:

```python
from daseg.data import DialogActCorpus, Call, FunctionalSegment

data = DialogActCorpus(
  dialogues={
    "some_call_id": Call(
      FunctionalSegment(text=item["utterance"], dialog_act=item["label"], speaker=item["speaker"])
      for item in my_data
    )
  }
)
```

Then you'll want to follow the steps as in [`prepare_exp`](https://github.com/pzelasko/daseg/blob/34ebb4425cb38f4dc04d8613d5fe23a561b18990/daseg/bin/dasg#L113) CLI utility, specifically the part below. Some comments: 
- `split_corpus` is a `DialogActCorpus` object, just for a single train/dev/test split;
- you need to initialize the model first to get a tokenizer
- `to_dataset` creates the `TensorDataset` you need
- saving the two pickle files at the end will let you use them as inputs to another CLI `dash train-transformer <args>`

https://github.com/pzelasko/daseg/blob/34ebb4425cb38f4dc04d8613d5fe23a561b18990/daseg/bin/dasg#L132-L151

I think it should "just work" but if you ran into any issues, feel free to follow up here.

**Comment by nuges01** [comment]
Awesome! It works great. Much appreciated.
