### ISSUE TITLE
Provide a trained checkpoint

### ISSUE THREAD

**Issue by maiiabocharova** [pzelasko/daseg#7]
Can you please provide a trained checkpoint to download and use just for inference without the need to train the model.

**Comment by pzelasko** [comment]
Hi Maiia, I can try to upload sth tomorrow. Ping me if  I haven’t done so by the end of the week.

**Comment by maiiabocharova** [comment]
> Hi Maiia, I can try to upload sth tomorrow. Ping me if I haven’t done so by the end of the week.

Thanks a lot!

**Comment by pzelasko** [comment]
I'm uploading one model to HF hub, should appear at this link in a few minutes. Loading it might require slight changes in `TransformerModel` class but I'm not sure right now -- let me know in case you're not able to figure it out. If this model works alright I can upload more of them.

https://huggingface.co/pzelasko/longformer-swda-nolower

**Comment by maiiabocharova** [comment]
> Glad to hear it’s useful :) there is some code in this repo which is able to parse the model predictions into functional segments and visualize them like in the paper, if that’s helpful.

Yes, that also would be helpful) Can you give me a hint to where to look for this functionality? (How the file is called)

**Comment by pzelasko** [comment]
This is the top level method that runs the prediction https://github.com/pzelasko/daseg/blob/5e3aaf6e81a44a5eb42226bd376c92c7d1879261/daseg/models/transformer_model.py#L94, it expects the data to be wrapped into DialogActCorpus. You can probably get away with not using it if you modify “predictions_to_dataset” function a bit so that it does not rely on ground truth dataset (it was useful for me because it matches ground truth and predictions by IDs so I could compare them easily)

**Comment by maiiabocharova** [comment]
> This is the top level method that runs the prediction
> 
> https://github.com/pzelasko/daseg/blob/5e3aaf6e81a44a5eb42226bd376c92c7d1879261/daseg/models/transformer_model.py#L94
> 
> , it expects the data to be wrapped into DialogActCorpus. You can probably get away with not using it if you modify “predictions_to_dataset” function a bit so that it does not rely on ground truth dataset (it was useful for me because it matches ground truth and predictions by IDs so I could compare them easily)

Thank a lot for your help! And all the work!

**Comment by maiiabocharova** [comment]
> This is the top level method that runs the prediction
> 
> https://github.com/pzelasko/daseg/blob/5e3aaf6e81a44a5eb42226bd376c92c7d1879261/daseg/models/transformer_model.py#L94
> 
> , it expects the data to be wrapped into DialogActCorpus. You can probably get away with not using it if you modify “predictions_to_dataset” function a bit so that it does not rely on ground truth dataset (it was useful for me because it matches ground truth and predictions by IDs so I could compare them easily)

I am very-very sorry to bother you once again, but can you also give an example of the input conversation for inference? (Like what token should be added between utterances). I read in your paper that there should be some separation "turn" token, but I can't find it in the code. So example would be extremely helpful.

**Comment by pzelasko** [comment]
The token is `<TURN>`, see this file for more definitions and utilities to see how the data is prepared:

https://github.com/pzelasko/daseg/blob/master/daseg/data.py#L42

In general I recommend running `./install.sh` which fetches SWDA and MRDA data, and then running sth like the following in a jupyter notebook

```python
from daseg import DialogActCorpus

corpus = DialogActCorpus.from_swda_path("deps/swda/swda")
call = corpus.calls[0]
call.render()
```

You can run `dasg prepare-exp` or `dasg evaluate` in the command line and trace back in the file below what happens to the conversation data to transform it into tensors

https://github.com/pzelasko/daseg/blob/master/daseg/bin/dasg#L110
